steps:
    - name: node:18.13.0
      entrypoint: npm
      args: ['install']
    - name: node:18.13.0
      entrypoint: npm
      args: ['run', 'create-env']
      env:
          - 'DB_HOST=${_DB_HOST}'
          - 'DB_USER=${_DB_USER}'
          - 'DB_DATABASE=${_DB_DATABASE}'
          - 'DB_PASSWORD=${_DB_PASSWORD}'
          - 'JWT_SECRET=${_JWT_SECRET}'
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', 'app.yaml']
timeout: '1600s'
options:
    logging: CLOUD_LOGGING_ONLY
